server:
  port: 8081

spring:
  profiles:
    active:
      - local

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: utf-8
    cache: false
    servlet:
      content-type: text/html

wx:
  # 公众号（包括订阅号和服务号）
  mp:
    app-id:
    secret:
    token:
    aesKey:
    config-storage: memory

  # 微信支付
  pay:
    app-id:
    mchId:
    mchKey:
    keyPath: